import Head from 'next/head'
import { Inter } from 'next/font/google'
import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Main from '@/components/Main'
import Partners from '@/components/Partners'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <Header />
        <Main />
        <Partners />
        <h1>Hello world</h1>
        <Footer/>
      </main>
    </>
  )
}

//https://www.figma.com/file/ph5HelCiamEC5EY5FXMmUk/Shopping-Website-(Community)-(Copy)?type=design&node-id=2-2&t=AdQGA0m1CGsWFpCI-0
